spring:
  application:
    name: meotsa-hackathon-be

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8080
  forward-headers-strategy: framework

jwt:
  secret: ${JWT_SECRET}
  access-expiration: 86400000    # 24시간 (임시, 원래 3600000=1시간)
  refresh-expiration: 1209600000 # 14일

cors:
  allowed-origins: http://localhost:5173, https://hackathon-hufs3.vercel.app

aws:
  region: ap-northeast-2
  s3:
    bucket: meotsa-hackathon-s3
  sqs:
    queue-url: https://sqs.ap-northeast-2.amazonaws.com/303764379155/meotsa-3d-jobs.fifo
  cloudfront:
    domain: d15xvovmn68oyr.cloudfront.net
  credentials:
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}

openai:
  api-key: ${OPENAI_API_KEY}
  base-url: https://api.openai.com/v1
  model: gpt-image-2
  size: 1024x1024
  quality: medium
  timeout: 180s